[project]
name = "doris"
version = "0.2.2"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "langchain-core>=1.2.7",
    "langchain-ollama>=1.0.1",
    "pyqt6>=6.10.2",
    "torch>=2.10.0",
    "transformers>=5.0.0",
]
